// flow-typed signature: 7eefe9d0eb2011432b71a609196f8cb3
// flow-typed version: <<STUB>>/aes-js_v^3.1.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aes-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aes-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aes-js/test/index' {
  declare module.exports: any;
}

declare module 'aes-js/test/test-aes' {
  declare module.exports: any;
}

declare module 'aes-js/test/test-buffer' {
  declare module.exports: any;
}

declare module 'aes-js/test/test-counter' {
  declare module.exports: any;
}

declare module 'aes-js/test/test-errors' {
  declare module.exports: any;
}

declare module 'aes-js/test/test-padding' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aes-js/index' {
  declare module.exports: $Exports<'aes-js'>;
}
declare module 'aes-js/index.js' {
  declare module.exports: $Exports<'aes-js'>;
}
declare module 'aes-js/test/index.js' {
  declare module.exports: $Exports<'aes-js/test/index'>;
}
declare module 'aes-js/test/test-aes.js' {
  declare module.exports: $Exports<'aes-js/test/test-aes'>;
}
declare module 'aes-js/test/test-buffer.js' {
  declare module.exports: $Exports<'aes-js/test/test-buffer'>;
}
declare module 'aes-js/test/test-counter.js' {
  declare module.exports: $Exports<'aes-js/test/test-counter'>;
}
declare module 'aes-js/test/test-errors.js' {
  declare module.exports: $Exports<'aes-js/test/test-errors'>;
}
declare module 'aes-js/test/test-padding.js' {
  declare module.exports: $Exports<'aes-js/test/test-padding'>;
}
