// flow-typed signature: ecb0c75383685a3ea9723a279a488f80
// flow-typed version: <<STUB>>/airbitz-core-types_vgit+https://github.com/Airbitz/airbitz-core-types.git/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'airbitz-core-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'airbitz-core-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'airbitz-core-types/indexAbcTypes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'airbitz-core-types/indexAbcTypes.js' {
  declare module.exports: $Exports<'airbitz-core-types/indexAbcTypes'>;
}
