// flow-typed signature: f3c302daae856c5e82039e800f6c7bbf
// flow-typed version: <<STUB>>/babel-plugin-fast-async_v^6.1.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-fast-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-fast-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-fast-async/plugin' {
  declare module.exports: any;
}

declare module 'babel-plugin-fast-async/tests/test-input' {
  declare module.exports: any;
}

declare module 'babel-plugin-fast-async/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-fast-async/plugin.js' {
  declare module.exports: $Exports<'babel-plugin-fast-async/plugin'>;
}
declare module 'babel-plugin-fast-async/tests/test-input.js' {
  declare module.exports: $Exports<'babel-plugin-fast-async/tests/test-input'>;
}
declare module 'babel-plugin-fast-async/tests/test.js' {
  declare module.exports: $Exports<'babel-plugin-fast-async/tests/test'>;
}
