// flow-typed signature: 63e94491736f1452432a8cb05ee9ef6a
// flow-typed version: <<STUB>>/base-x_v^1.0.4/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'base-x'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'base-x' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'base-x/index' {
  declare module.exports: $Exports<'base-x'>;
}
declare module 'base-x/index.js' {
  declare module.exports: $Exports<'base-x'>;
}
