// flow-typed signature: 0c7ce2e51ce7db809f5f3827846fbf55
// flow-typed version: <<STUB>>/currency-codes_v^1.1.2/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'currency-codes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'currency-codes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'currency-codes/data' {
  declare module.exports: any;
}

declare module 'currency-codes/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'currency-codes/data.js' {
  declare module.exports: $Exports<'currency-codes/data'>;
}
declare module 'currency-codes/index' {
  declare module.exports: $Exports<'currency-codes'>;
}
declare module 'currency-codes/index.js' {
  declare module.exports: $Exports<'currency-codes'>;
}
declare module 'currency-codes/test.js' {
  declare module.exports: $Exports<'currency-codes/test'>;
}
