// flow-typed signature: 346fd6b98d95596869c20fa5ff7a4441
// flow-typed version: <<STUB>>/disklet_v^0.2.2/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'disklet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'disklet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'disklet/lib/disklet.cjs' {
  declare module.exports: any;
}

declare module 'disklet/lib/disklet' {
  declare module.exports: any;
}

declare module 'disklet/lib/disklet.rn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'disklet/lib/disklet.cjs.js' {
  declare module.exports: $Exports<'disklet/lib/disklet.cjs'>;
}
declare module 'disklet/lib/disklet.js' {
  declare module.exports: $Exports<'disklet/lib/disklet'>;
}
declare module 'disklet/lib/disklet.rn.js' {
  declare module.exports: $Exports<'disklet/lib/disklet.rn'>;
}
