// flow-typed signature: 1c291b120a5c64674b4d403cc21eb45a
// flow-typed version: <<STUB>>/redux-keto_v^0.3.2/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-keto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-keto' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-keto/lib/redux-keto.es' {
  declare module.exports: any;
}

declare module 'redux-keto/lib/redux-keto' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-keto/lib/redux-keto.es.js' {
  declare module.exports: $Exports<'redux-keto/lib/redux-keto.es'>;
}
declare module 'redux-keto/lib/redux-keto.js' {
  declare module.exports: $Exports<'redux-keto/lib/redux-keto'>;
}
