// flow-typed signature: 5cbca26b8f82afddb9b000dacc130b58
// flow-typed version: <<STUB>>/rfc4648_v^1.0.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rfc4648'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rfc4648' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rfc4648/lib/base16' {
  declare module.exports: any;
}

declare module 'rfc4648/lib/base32' {
  declare module.exports: any;
}

declare module 'rfc4648/lib/base32hex' {
  declare module.exports: any;
}

declare module 'rfc4648/lib/base64' {
  declare module.exports: any;
}

declare module 'rfc4648/lib/base64url' {
  declare module.exports: any;
}

declare module 'rfc4648/lib/codec' {
  declare module.exports: any;
}

declare module 'rfc4648/lib/index.cjs' {
  declare module.exports: any;
}

declare module 'rfc4648/lib/index' {
  declare module.exports: any;
}

declare module 'rfc4648/lib/index.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rfc4648/lib/base16.js' {
  declare module.exports: $Exports<'rfc4648/lib/base16'>;
}
declare module 'rfc4648/lib/base32.js' {
  declare module.exports: $Exports<'rfc4648/lib/base32'>;
}
declare module 'rfc4648/lib/base32hex.js' {
  declare module.exports: $Exports<'rfc4648/lib/base32hex'>;
}
declare module 'rfc4648/lib/base64.js' {
  declare module.exports: $Exports<'rfc4648/lib/base64'>;
}
declare module 'rfc4648/lib/base64url.js' {
  declare module.exports: $Exports<'rfc4648/lib/base64url'>;
}
declare module 'rfc4648/lib/codec.js' {
  declare module.exports: $Exports<'rfc4648/lib/codec'>;
}
declare module 'rfc4648/lib/index.cjs.js' {
  declare module.exports: $Exports<'rfc4648/lib/index.cjs'>;
}
declare module 'rfc4648/lib/index.js' {
  declare module.exports: $Exports<'rfc4648/lib/index'>;
}
declare module 'rfc4648/lib/index.min.js' {
  declare module.exports: $Exports<'rfc4648/lib/index.min'>;
}
