// flow-typed signature: 81e100b773a8e31e9ec95d3492e0e9ff
// flow-typed version: <<STUB>>/scrypt-js_v^2.0.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scrypt-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scrypt-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scrypt-js/scrypt' {
  declare module.exports: any;
}

declare module 'scrypt-js/test/test-scrypt' {
  declare module.exports: any;
}

declare module 'scrypt-js/thirdparty/buffer' {
  declare module.exports: any;
}

declare module 'scrypt-js/thirdparty/setImmediate' {
  declare module.exports: any;
}

declare module 'scrypt-js/thirdparty/unorm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scrypt-js/scrypt.js' {
  declare module.exports: $Exports<'scrypt-js/scrypt'>;
}
declare module 'scrypt-js/test/test-scrypt.js' {
  declare module.exports: $Exports<'scrypt-js/test/test-scrypt'>;
}
declare module 'scrypt-js/thirdparty/buffer.js' {
  declare module.exports: $Exports<'scrypt-js/thirdparty/buffer'>;
}
declare module 'scrypt-js/thirdparty/setImmediate.js' {
  declare module.exports: $Exports<'scrypt-js/thirdparty/setImmediate'>;
}
declare module 'scrypt-js/thirdparty/unorm.js' {
  declare module.exports: $Exports<'scrypt-js/thirdparty/unorm'>;
}
