// flow-typed signature: 8d88084018b4ae87a8ad10da49662f67
// flow-typed version: <<STUB>>/utf8_v^2.1.2/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'utf8'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'utf8' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'utf8/utf8' {
  declare module.exports: any;
}

// Filename aliases
declare module 'utf8/utf8.js' {
  declare module.exports: $Exports<'utf8/utf8'>;
}
