/**
 * ABCConditionCode
 * Error codes for ABCError object
 */

export const abcc = {
  ABCConditionCodeOk: 0,
  ABCConditionCodeError: 1,
  ABCConditionCodeNULLPtr: 2,
  ABCConditionCodeNoAvailAccountSpace: 3,
  ABCConditionCodeDirReadError: 4,
  ABCConditionCodeFileOpenError: 5,
  ABCConditionCodeFileReadError: 6,
  ABCConditionCodeFileWriteError: 7,
  ABCConditionCodeFileDoesNotExist: 8,
  ABCConditionCodeUnknownCryptoType: 9,
  ABCConditionCodeInvalidCryptoType: 10,
  ABCConditionCodeDecryptError: 11,
  ABCConditionCodeDecryptFailure: 12,
  ABCConditionCodeEncryptError: 13,
  ABCConditionCodeScryptError: 14,
  ABCConditionCodeAccountAlreadyExists: 15,
  ABCConditionCodeAccountDoesNotExist: 16,
  ABCConditionCodeJSONError: 17,
  ABCConditionCodeBadPassword: 18,
  ABCConditionCodeWalletAlreadyExists: 19,
  ABCConditionCodeURLError: 20,
  ABCConditionCodeSysError: 21,
  ABCConditionCodeNotInitialized: 22,
  ABCConditionCodeReinitialization: 23,
  ABCConditionCodeServerError: 24,
  ABCConditionCodeNoRecoveryQuestions: 25,
  ABCConditionCodeNotSupported: 26,
  ABCConditionCodeMutexError: 27,
  ABCConditionCodeNoTransaction: 28,
  ABCConditionCodeEmpty_Wallet: 28,
  ABCConditionCodeParseError: 29,
  ABCConditionCodeInvalidWalletID: 30,
  ABCConditionCodeNoRequest: 31,
  ABCConditionCodeInsufficientFunds: 32,
  ABCConditionCodeSynchronizing: 33,
  ABCConditionCodeNonNumericPin: 34,
  ABCConditionCodeNoAvailableAddress: 35,
  ABCConditionCodeInvalidPinWait: 36,
  ABCConditionCodePinExpired: 36,
  ABCConditionCodeInvalidOTP: 37,
  ABCConditionCodeSpendDust: 38,
  ABCConditionCodeObsolete: 1000
}
